let a = 145;
let b = 5;
console.log("a=" + a);
console.log("b=" + b);
console.log("a+b=" + (a + b));
console.log("a-b=" + (a - b));
console.log("a*b=" + (a * b));
console.log("a/b=" + (a / b));
console.log("Quest2");

let x = 6;
let y = 15;
let z = 4;
console.log("x=" + x);
console.log("y=" + y);
console.log("z=" + z);
x += y - x++ * z;
console.log("x += y - x++ * z=" + x);
z = --x - y * 5;
console.log("z = --x - y * 5=" + z);
y /= x + 5 % z;
console.log("y /= x + 5 % z=" + y);
z = x++ + y * 5;
console.log("z = x++ + y * 5" + z);
x = y - x++ * z;
console.log("x = y - x++ * z" + x);
console.log("Среднее для 5 10 и 30: " + (5 + 10 + 30) / 3);
let h = 10; let r = 7;
console.log("h=" + h);
console.log("r=" + r);
console.log("V=" + (Math.PI * Math.pow(r, 2) * h));
console.log("S=" + (2 * Math.PI * r * (r + h)));