let a = 145;
let b = 5;
document.write("Quest1 <br>");
document.write("a=" + a + "<br>");
document.write("b=" + b + "<br>");
document.write("a+b=" + (a + b) + "<br>");
document.write("a-b=" + (a - b) + "<br>");
document.write("a*b=" + (a * b) + "<br>");
document.write("a/b=" + (a / b) + "<br>");
document.write("<br> Quest3 <br>");

let x = 6;
let y = 15;
let z = 4;

document.write("x=" + x + "<br>");
document.write("y=" + y + "<br>");
document.write("z=" + z + "<br>");
x += y - x++ * z;
document.write("x += y - x++ * z=" + x + "<br>");
z = --x - y * 5;
document.write("z = --x - y * 5=" + z + "<br>");
y /= x + 5 % z;
document.write("y /= x + 5 % z=" + y + "<br>");
z = x++ + y * 5;
document.write("z = x++ + y * 5=" + z + "<br>");
x = y - x++ * z;
document.write("x = y - x++ * z=" + x + "<br>");
document.write("<br> Quest4 <br>");
document.write("Среднее для 5 10 и 30: " + (5 + 10 + 30) / 3 + "<br>");
let h = 10; let r = 7;
document.write("<br> Quest5 <br>");
document.write("h=" + h + "<br>");
document.write("r=" + r + "<br>");
document.write("V=" + (Math.PI * Math.pow(r, 2) * h) + "<br>");
document.write("S=" + (2 * Math.PI * r * (r + h)) + "<br>");